// 错误码定义

export const ERROR_CODES = {
  // 通用错误 400xxx
  BAD_REQUEST: 400000,
  VALIDATION_ERROR: 400001,
  INVALID_PARAMS: 400002,

  // 认证错误 401xxx
  UNAUTHORIZED: 401000,
  INVALID_TOKEN: 401001,
  TOKEN_EXPIRED: 401002,

  // 权限错误 403xxx
  FORBIDDEN: 403000,
  NO_PERMISSION: 403001,

  // 资源错误 404xxx
  NOT_FOUND: 404000,
  USER_NOT_FOUND: 404001,
  PROMPT_NOT_FOUND: 404002,
  DATASET_NOT_FOUND: 404003,
  MODEL_NOT_FOUND: 404004,
  EVALUATOR_NOT_FOUND: 404005,
  TASK_NOT_FOUND: 404006,
  PROVIDER_NOT_FOUND: 404007,
  PROJECT_NOT_FOUND: 404008,
  MEMBER_NOT_FOUND: 404009,
  API_TOKEN_NOT_FOUND: 404010,

  // 冲突错误 409xxx
  CONFLICT: 409000,
  EMAIL_EXISTS: 409001,
  NAME_EXISTS: 409002,
  MEMBER_EXISTS: 409003,
  CANNOT_REMOVE_OWNER: 409004,
  CANNOT_CHANGE_OWNER_ROLE: 409005,

  // 服务器错误 500xxx
  INTERNAL_ERROR: 500000,
  DATABASE_ERROR: 500001,
  REDIS_ERROR: 500002,
  EXTERNAL_API_ERROR: 500003,

  // 任务执行错误 501xxx
  TASK_EXECUTION_ERROR: 501000,
  TASK_TIMEOUT: 501001,
  EVALUATOR_ERROR: 501002,
  MODEL_API_ERROR: 501003,
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.BAD_REQUEST]: '请求错误',
  [ERROR_CODES.VALIDATION_ERROR]: '数据验证失败',
  [ERROR_CODES.INVALID_PARAMS]: '参数无效',

  [ERROR_CODES.UNAUTHORIZED]: '未授权',
  [ERROR_CODES.INVALID_TOKEN]: '无效的令牌',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期',

  [ERROR_CODES.FORBIDDEN]: '禁止访问',
  [ERROR_CODES.NO_PERMISSION]: '没有权限',

  [ERROR_CODES.NOT_FOUND]: '资源不存在',
  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.PROMPT_NOT_FOUND]: '提示词不存在',
  [ERROR_CODES.DATASET_NOT_FOUND]: '数据集不存在',
  [ERROR_CODES.MODEL_NOT_FOUND]: '模型不存在',
  [ERROR_CODES.EVALUATOR_NOT_FOUND]: '评估器不存在',
  [ERROR_CODES.TASK_NOT_FOUND]: '任务不存在',
  [ERROR_CODES.PROVIDER_NOT_FOUND]: '供应商不存在',
  [ERROR_CODES.PROJECT_NOT_FOUND]: '项目不存在',
  [ERROR_CODES.MEMBER_NOT_FOUND]: '成员不存在',
  [ERROR_CODES.API_TOKEN_NOT_FOUND]: 'API Token 不存在',

  [ERROR_CODES.CONFLICT]: '资源冲突',
  [ERROR_CODES.EMAIL_EXISTS]: '邮箱已存在',
  [ERROR_CODES.NAME_EXISTS]: '名称已存在',
  [ERROR_CODES.MEMBER_EXISTS]: '用户已是项目成员',
  [ERROR_CODES.CANNOT_REMOVE_OWNER]: '不能移除项目所有者',
  [ERROR_CODES.CANNOT_CHANGE_OWNER_ROLE]: '不能修改所有者角色',

  [ERROR_CODES.INTERNAL_ERROR]: '服务器内部错误',
  [ERROR_CODES.DATABASE_ERROR]: '数据库错误',
  [ERROR_CODES.REDIS_ERROR]: 'Redis 错误',
  [ERROR_CODES.EXTERNAL_API_ERROR]: '外部 API 错误',

  [ERROR_CODES.TASK_EXECUTION_ERROR]: '任务执行错误',
  [ERROR_CODES.TASK_TIMEOUT]: '任务超时',
  [ERROR_CODES.EVALUATOR_ERROR]: '评估器执行错误',
  [ERROR_CODES.MODEL_API_ERROR]: '模型 API 调用错误',
}
